<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Bpmn.Model/Bpmn.Model.csproj" />
    <ProjectReference Include="../../src/Bpmn.Interchange/Bpmn.Interchange.csproj" />
    <ProjectReference Include="../../src/Bpmn.Semantics/Bpmn.Semantics.csproj" />
    <ProjectReference Include="../../src/Bpmn.Runtime.InMemory/Bpmn.Runtime.InMemory.csproj" />
  </ItemGroup>
</Project>
